server:
    port: 8080

liquibase:
    context: dev

spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://hillromvest.ckyg8erbez54.us-west-2.rds.amazonaws.com:3306/hillromvest_dev?zeroDateTimeBehavior=convertToNull
        databaseName:
        serverName:
        username: root
        password: Hillrom123
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: com.hillrom.vest.repository.util.CustomMySQL5InnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    messages:
        cache-seconds: 1
    thymeleaf:
        mode: XHTML
        cache: false
        check-template-location: false
    recaptcha:
        recaptchaPrivateKey: 6LcXjQkTAAAAACiA7rx7o7wlifQ7n3VQ_It-sncc
    notification:
        hcpOrClinicAdminDashboardUrl: http://devserver.hillromvest.com
        patientDashboardUrl: http://devserver.hillromvest.com
        careGiverDashboardUrl: http://devserver.hillromvest.com
        baseUrl: http://devserver.hillromvest.com
        accountActivationReminderInterval: 72

    survey:
        surveyreportemailids: vijayanand.jayapal@lnttechservices.com,nagendra.tv@lnttechservices.com
    changePrescription:
        changePrescriptionEmailids: vijayanand.jayapal@lnttechservices.com,nagendra.tv@lnttechservices.com
        
    timsLog:
        timsLogEmailids: abhishek.tiwari@lnttechservices.com,Sravan.Ballu@LntTechservices.com,Raghu.NT@Lnttechservices.com,nagendra.tv@lnttechservices.com,Ravichandra.BM@LntTechservices.com