# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 9a643507ff3724079e186ec884447a3875a61090

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

mail:
    host: smtp.gmail.com
    port: 587
    username: test.hillrom@gmail.com
    password: hillrom12345
    protocol: smtp
    tls: true
    auth: true
    from: test.hillrom@gmail.com
    to: gopakumar@neevtech.com,rohan.kushwaha@neevtech.com,raghu.narayanan@neevtech.com,nagendra@neevtech.com
    surveyreportemailids: amit.saurabh@neevtech.com,nagendra@neevtech.com
authentication:
    xauth:
        secret: myXAuthSecret
        # Token is valid 30 minutes
        tokenValidityInSeconds: 1800

spring.batch.job.enabled: false
