server:
    port: 8080

liquibase:
    context: prod

spring:
    profiles:
        active: prod
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://Indsugrc01vd:3306/hillromvest_prod?zeroDateTimeBehavior=convertToNull
        databaseName: 
        serverName: 
        username: root
        password: Hillrom123
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: com.hillrom.vest.repository.util.CustomMySQL5InnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    messages:
        cache-seconds: 1
    thymeleaf:
        mode: XHTML
        cache: false
        check-template-location: false
    recaptcha:
        recaptchaPrivateKey: 6LcXjQkTAAAAACiA7rx7o7wlifQ7n3VQ_It-sncc
    notification:
        hcpOrClinicAdminDashboardUrl: https://visiview.hill-rom.com
        patientDashboardUrl: https://visiview.hill-rom.com
        careGiverDashboardUrl: https://visiview.hill-rom.com
        baseUrl: https://visiview.hill-rom.com
        accountActivationReminderInterval: 72
    survey:

        surveyreportemailids: vijayanand.jayapal@lnttechservices.com,nagendra.tv@lnttechservices.com,raghu.nt@lnttechservices.com 
    changePrescription:
        changePrescriptionEmailids: vijayanand.jayapal@lnttechservices.com,nagendra.tv@lnttechservices.com,raghu.nt@lnttechservices.com
