server:
    port: 8080

liquibase:
    context: uat

spring:
    profiles:
        active: uat
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://indoffshre02v.hillromvest.com:3306/hillromvest_prod
        databaseName:
        serverName:
        username: root
        password: Hillrom123
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    messages:
        cache-seconds: 1
    thymeleaf:
        mode: XHTML
        cache: false
        check-template-location: false
    recaptcha:
        recaptchaPrivateKey: 6LcXjQkTAAAAACiA7rx7o7wlifQ7n3VQ_It-sncc
    notification:
        hcpOrClinicAdminDashboardUrl: http://indoffshre01v.hillromvest.com
        patientDashboardUrl: http://indoffshre01v.hillromvest.com
        careGiverDashboardUrl: http://indoffshre01v.hillromvest.com
        baseUrl: http://indoffshre01v.hillromvest.com
        accountActivationReminderInterval: 12
    survey:
        surveyreportemailids: nagendra.shetty@razorfish.com,amit.saurabh@razorfish.com,anubhav.sinha@razorfish.com,nagendra@neevtech.com,amit.saurabh@neevtech.com
    changePrescription:
        changePrescriptionEmailids: nagendra.shetty@razorfish.com,amit.saurabh@razorfish.com,anubhav.sinha@razorfish.com,nagendra@neevtech.com,amit.saurabh@neevtech.com
